spring: 
  profiles:
    active: dev
---
server:
    port: 4001
spring:
  profiles: dev
  applicaion:
    name: microserivce-config-dev
---
server:
  port: 4002
spring:
  profiles: prod
  application: 
    name: microserivce-config-prod  
	
